- hosts: all
  become_user: root
  become_method: sudo
  become: yes


  tasks:
    - name: create demo file
      command: touch /etc/demo.txt
      args:
        chdir: /etc

    - name: print the list of content in one file
      command: echo "hello World" >> /etc/demo.txt
      args:
        chdir: /etc
