- hosts: webservers
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes
  

  tasks:
     - name: install apache on remote server
       apt:
         name: apache2
         update_cache: yes
         state: latest
     - name: enable the service
       service:
           enabled: true
           name: apache2
           state: started
     - name: copy index.html file from local to remote 
       copy:
         src: /etc/ansible/files/index.html
         dest: /var/www/html/index.html
