- hosts: all
  become_user: root
  become_method: sudo
  become: yes


  vars: 
    package_name: apache2


  tasks: 
    - name: generate some template config and send it to remote server
      template: 
         src: template-j2.j2
         dest: /opt/result.txt  
