- hosts: webservers
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes

  vars:
    package_name: apache2
    service_name: apache2
    destination_path: /var/www/html
    index_file: index.html
  

  tasks:
     - name: install apache on remote server
       apt:
         name: "{{package_name}}"
         update_cache: yes
         state: latest
     - name: enable the service
       service:
           enabled: true
           name: "{{service_name}}"
           state: started
     - name: copy index.html file from local to remote 
       copy:
         src: "/etc/ansible/files/{{index_file}}"
         dest: "{{destination_path}}/{{index_file}}"
